### ISSUE TITLE
Unable to add a new colour light if in temperature mode

### ISSUE THREAD

**Issue by ad5665** [Pyhive/Pyhiveapi#12]
**Describe the bug**
After installing the HA-Hive-Custom-Component, when the component was finding my lights. It kept crashing when trying to add my 2 colourtuneablelights.

```
2021-02-14 13:59:20 ERROR (MainThread) [homeassistant.components.light] hive: Error on device update!
Traceback (most recent call last):
  File "/opt/homeassistant/lib64/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 358, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/opt/homeassistant/lib64/python3.9/site-packages/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/home/homeassistant/.homeassistant/custom_components/hive/light.py", line 160, in async_update
    self.device = await self.hive.light.get_light(self.device)
  File "/opt/homeassistant/lib64/python3.9/site-packages/pyhiveapi/light.py", line 59, in get_light
    "hs_color": await self.get_color(device),
  File "/opt/homeassistant/lib64/python3.9/site-packages/pyhiveapi/light.py", line 156, in get_color
    (data["state"]["hue"]) / 360,
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int
```

We've found if a colourtuneablelight does not have a colour, but a temperature selected. When it gets to this part in light.py

```
 if device["hiveType"] == "colourtuneablelight":
                dev_data["status"].update(
                    {
                        "hs_color": await self.get_color(device),
                        "mode": await self.getColourMode(device),
                    }
                )
```
`self.get_color(device)`, returns nothing. 
This can be seen after the lights have been added in Developer Tools

Temperature selected
```
min_mireds: 153
max_mireds: 370
brightness: 127.5
color_temp: 332
available: true
mode: MANUAL
friendly_name: Left lamp
supported_features: 19
```

vs colour selected
```
min_mireds: 153
max_mireds: 370
brightness: 255
color_temp: 370
hs_color:
  - 285
  - 28.235
rgb_color:
  - 237
  - 183
  - 255
xy_color:
  - 0.329
  - 0.25
available: true
mode: MANUAL
friendly_name: Right lamp
supported_features: 19
```

**Expected behavior**
Colour light will be added, even when in temperature mode. 

**Additional context**
Once the light are in HA, they seem to be fine after restarting the HA service and reloading the Hive integration.

Cheers

**Comment by ad5665** [comment]
https://github.com/Pyhive/Pyhiveapi/pull/13

**Comment by KJonline** [comment]
@ad5665 

thanks for raising this it will be fixed in the next version of the custom component.
